./cpp_func_name_FuncRenameChangeChar.sh
./cpp_func_name_FuncRenameButterFinger.sh
./cpp_func_name_FuncRenameSynonymSub.sh
./cpp_func_name_FuncRenameSwapChar.sh
./cpp_func_name_FuncRenameInflectionalVariation.sh
./cpp_func_name_FuncRenameSnakeCase.sh
./cpp_func_name_FuncRenameCamelCase.sh
./cpp_format_split_lines.sh
./cpp_format_tab_indent.sh
./cpp_format_doc2comments.sh
./cpp_format_new_line_aftercode.sh
./cpp_format_new_line_afterdoc.sh
./cpp_format_new_lines.sh
./cpp_nlaugmenter_SynonymSubstitution.sh
./cpp_nlaugmenter_SynonymInsertion.sh
./cpp_nlaugmenter_ButterFingersPerturbation.sh
./cpp_nlaugmenter_TenseTransformationPast.sh
./cpp_nlaugmenter_WhitespacePerturbation.sh
./cpp_nlaugmenter_SwapCharactersPerturbation.sh
./cpp_nlaugmenter_TenseTransformationFuture.sh
./cpp_nlaugmenter_BackTranslation.sh
./cpp_nlaugmenter_ChangeCharCase.sh
./cpp_nlaugmenter_EnglishInflectionalVariation.sh
./cpp_natgen_VarRenamerNaive.sh
./cpp_natgen_VarRenamerRN.sh
./cpp_natgen_OperandSwap.sh
./cpp_natgen_DeadCodeInserter.sh
./cpp_natgen_VarRenamerCB.sh
./cpp_natgen_ForWhileTransformer.sh
