./js_func_name_FuncRenameButterFinger.sh
./js_func_name_FuncRenameInflectionalVariation.sh
./js_func_name_FuncRenameChangeChar.sh
./js_func_name_FuncRenameSnakeCase.sh
./js_func_name_FuncRenameSwapChar.sh
./js_func_name_FuncRenameSynonymSub.sh
./js_format_tab_indent.sh
./js_format_new_lines.sh
./js_format_split_lines.sh
./js_format_new_line_aftercode.sh
./js_format_new_line_afterdoc.sh
./js_format_doc2comments.sh
./js_nlaugmenter_BackTranslation.sh
./js_nlaugmenter_ButterFingersPerturbation.sh
./js_nlaugmenter_SynonymSubstitution.sh
./js_nlaugmenter_WhitespacePerturbation.sh
./js_nlaugmenter_EnglishInflectionalVariation.sh
./js_nlaugmenter_TenseTransformationFuture.sh
./js_nlaugmenter_SwapCharactersPerturbation.sh
./js_nlaugmenter_SynonymInsertion.sh
./js_nlaugmenter_ChangeCharCase.sh
./js_nlaugmenter_TenseTransformationPast.sh
./js_natgen_OperandSwap.sh
./js_natgen_DeadCodeInserter.sh
./js_natgen_VarRenamerNaive.sh
./js_natgen_ForWhileTransformer.sh
./js_natgen_VarRenamerCB.sh
./js_natgen_VarRenamerRN.sh
