./java_func_name_FuncRenameSnakeCase.sh
./java_func_name_FuncRenameInflectionalVariation.sh
./java_func_name_FuncRenameButterFinger.sh
./java_func_name_FuncRenameSynonymSub.sh
./java_func_name_FuncRenameChangeChar.sh
./java_func_name_FuncRenameSwapChar.sh
./java_format_new_line_aftercode.sh
./java_format_doc2comments.sh
./java_format_tab_indent.sh
./java_format_new_line_afterdoc.sh
./java_format_new_lines.sh
./java_format_split_lines.sh
./java_nlaugmenter_TenseTransformationPast.sh
./java_nlaugmenter_ChangeCharCase.sh
./java_nlaugmenter_SynonymInsertion.sh
./java_nlaugmenter_BackTranslation.sh
./java_nlaugmenter_SynonymSubstitution.sh
./java_nlaugmenter_WhitespacePerturbation.sh
./java_nlaugmenter_ButterFingersPerturbation.sh
./java_nlaugmenter_EnglishInflectionalVariation.sh
./java_nlaugmenter_TenseTransformationFuture.sh
./java_nlaugmenter_SwapCharactersPerturbation.sh
./java_natgen_ForWhileTransformer.sh
./java_natgen_OperandSwap.sh
./java_natgen_VarRenamerRN.sh
./java_natgen_DeadCodeInserter.sh
./java_natgen_VarRenamerNaive.sh
./java_natgen_VarRenamerCB.sh
