cd ..
python generate_single_code_multiple_gpu.py ../datasets/perturbed/humanevaljava/full/nlaugmenter/humanevaljava_EnglishInflectionalVariation_s0.jsonl ../datasets/generated_pass5_1/java/nlaugmenter/EnglishInflectionalVariation
python generate_single_code_multiple_gpu.py ../datasets/perturbed/humanevaljava/full/nlaugmenter/humanevaljava_EnglishInflectionalVariation_s2.jsonl ../datasets/generated_pass5_1/java/nlaugmenter/EnglishInflectionalVariation
python generate_single_code_multiple_gpu.py ../datasets/perturbed/humanevaljava/full/nlaugmenter/humanevaljava_EnglishInflectionalVariation_s1.jsonl ../datasets/generated_pass5_1/java/nlaugmenter/EnglishInflectionalVariation
python generate_single_code_multiple_gpu.py ../datasets/perturbed/humanevaljava/full/nlaugmenter/humanevaljava_EnglishInflectionalVariation_s4.jsonl ../datasets/generated_pass5_1/java/nlaugmenter/EnglishInflectionalVariation
python generate_single_code_multiple_gpu.py ../datasets/perturbed/humanevaljava/full/nlaugmenter/humanevaljava_EnglishInflectionalVariation_s3.jsonl ../datasets/generated_pass5_1/java/nlaugmenter/EnglishInflectionalVariation
